### PR TITLE
Generating output files for spheres

### PR DESCRIPTION
**Pull request by aysecanuenal**
Generating particle pose file from sphere annotations

### CODE REVIEW

**Review by alisterburt — COMMENTED** [review]
Awesome! 

Code/structure wise this looks great but it doesn't quite do the thing we're trying to do with sphere annotation. We often annotate spheres when we want to sample particle positions on the surface of the sphere with their z-vector normal to the sphere. 

Does that make sense? We would probably want to expose an additional parameter for the expected distance between particles. We can do the actual sampling from the surface using a library Kevin and I put together a while ago called morphosamplers. Here is [an example](https://github.com/morphometrics/morphosamplers/blob/main/examples/sphere.py) demonstrating using that library for sampling on the sphere. You would then need to convert the rotation matrices into Euler angles (probably RELION compatible makes the most sense) to save them easily :-)

**Comment by aysecanuenal** [comment]
Yes, it makes perfect sense and this was quite straightforward with morphosamplers and the example :partying_face: Thank you very much!

Here is an updated version. Just 2 quick questions/checks now before some more additions/changes: So, the distance between particles should be an additional parameter that the user inputs? aaannddd is this where we convert the rotation matrices into Euler angles or during export part?

**Review by alisterburt — COMMENTED** [review]
@aysecanuenal amazing! Looks great - you'll need to add the morphosamplers dependency to pyproject.toml 

Yes the spacing parameter here should also be passed at the CLI as you said ☺️ 

The Euler angle conversion would be good but let's do that in a follow up PR, I'll find an example of saving RELION Euler angles from matrices for you. The reason to do this is it's not super clean to have three values in a single column and the vectors are a bit less interpretable

**Review by alisterburt — APPROVED** [review]
Looks perfect @aysecanuenal ! Great work :-)

**Pull request merged**
